/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CharacterByLocationIndexImport } from './routes/character-by-location/index'
import { Route as ListCharacterLocationLocationNameImport } from './routes/list-character-location/$locationName'
import { Route as CharacterCharacterIdImport } from './routes/character/$characterId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CharacterByLocationIndexRoute = CharacterByLocationIndexImport.update({
  path: '/character-by-location/',
  getParentRoute: () => rootRoute,
} as any)

const ListCharacterLocationLocationNameRoute =
  ListCharacterLocationLocationNameImport.update({
    path: '/list-character-location/$locationName',
    getParentRoute: () => rootRoute,
  } as any)

const CharacterCharacterIdRoute = CharacterCharacterIdImport.update({
  path: '/character/$characterId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/character/$characterId': {
      id: '/character/$characterId'
      path: '/character/$characterId'
      fullPath: '/character/$characterId'
      preLoaderRoute: typeof CharacterCharacterIdImport
      parentRoute: typeof rootRoute
    }
    '/list-character-location/$locationName': {
      id: '/list-character-location/$locationName'
      path: '/list-character-location/$locationName'
      fullPath: '/list-character-location/$locationName'
      preLoaderRoute: typeof ListCharacterLocationLocationNameImport
      parentRoute: typeof rootRoute
    }
    '/character-by-location/': {
      id: '/character-by-location/'
      path: '/character-by-location'
      fullPath: '/character-by-location'
      preLoaderRoute: typeof CharacterByLocationIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CharacterCharacterIdRoute,
  ListCharacterLocationLocationNameRoute,
  CharacterByLocationIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/character/$characterId",
        "/list-character-location/$locationName",
        "/character-by-location/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/character/$characterId": {
      "filePath": "character/$characterId.tsx"
    },
    "/list-character-location/$locationName": {
      "filePath": "list-character-location/$locationName.tsx"
    },
    "/character-by-location/": {
      "filePath": "character-by-location/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
